global:
  scrape_interval: 5s 

scrape_configs:
  - job_name: 'api_services'
    metrics_path: /metrics
    static_configs:
      - targets:
          - '172.31.209.76:5001' # Delete
          - '172.31.209.76:5005' # Get
          - '172.31.209.76:5006'  # Add
          - '172.31.209.76:5007' # Update

  - job_name: 'rabbitmq'
    metrics_path: /metrics
    static_configs:
      - targets:
          - rabbitmq:15692

  - job_name: 'postgres'
    static_configs:
      - targets: ['172.31.209.76:9187']
  
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['172.31.209.76:9100']
