apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: registro-contato
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s 

    scrape_configs:
      - job_name: 'api_services'
        metrics_path: /metrics
        static_configs:
          - targets:
              - 'delete-contato.registro-contato.svc.cluster.local:5001' 
              - 'get-contato.registro-contato.svc.cluster.local:5005'
              - 'add-contato-producer.registro-contato.svc.cluster.local:5006'
              - 'update-contato-producer.registro-contato.svc.cluster.local:5007'

      - job_name: 'rabbitmq'
        metrics_path: /metrics
        static_configs:
          - targets:
              - rabbitmq.registro-contato.svc.cluster.local:15692

      - job_name: 'postgres'
        static_configs:
          - targets: ['postgres-exporter.registro-contato.svc.cluster.local:9187']

      - job_name: 'node_exporter'
        static_configs:
          - targets: ['node-exporter.registro-contato.svc.cluster.local:9100']
