name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configurar cache do NuGet
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Limpar cache NuGet
        run: dotnet nuget locals all --clear

      - name: Restaurar dependências da solução
        run: dotnet restore

      - name: Criar `.env` para variáveis de ambiente
        run: cp .env.example .env

      - name: Construir containers do projeto
        run: docker compose build --no-cache

      - name: Subir os containers e aguardar serviços estarem prontos
        run: docker compose up -d

      - name: Aguardar RabbitMQ e PostgreSQL ficarem saudáveis
        run: |
          echo "Aguardando RabbitMQ e PostgreSQL..."
          sleep 30

      - name: Executar testes unitários
        run: docker compose run --rm tests-unit

      - name: Executar testes de integração
        run: docker compose run --rm tests-integration

      - name: Parar e remover containers
        run: docker compose down